# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [6]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.45331871, 0.5296934 , 0.61287974, 0.12976386, 0.28346094])

In [17]:
np.random.rand(5,5)

array([[0.17082129, 0.38548267, 0.17091387, 0.99869906, 0.08183769],
       [0.99964913, 0.88967708, 0.67254812, 0.5978414 , 0.82202221],
       [0.2344343 , 0.63900984, 0.16740703, 0.63116465, 0.8406886 ],
       [0.9175344 , 0.21033817, 0.53818417, 0.17197936, 0.82997822],
       [0.46897165, 0.92747272, 0.76481875, 0.56174603, 0.21499909]])

In [19]:
np.random.randn(4,4)

array([[ 1.45114223,  0.48620254,  0.69765589, -1.19315453],
       [-1.05140158,  0.48945867, -1.34072197,  0.34987217],
       [-0.4799478 ,  0.70006694, -1.38887129,  0.05064541],
       [-0.44784724, -1.16805132, -0.62617699,  0.71772392]])

In [22]:
np.random.randint(1,100,10)

array([65, 71, 99, 93, 37, 90, 60, 69, 86, 44])

In [23]:
arr =np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,50,10)

In [26]:
ranarr 

array([45, 17,  5, 19, 38, 46, 39, 38, 49, 35])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.argmax()

8

In [31]:
ranarr.argmin()

2

In [32]:
arr.shape

(25,)

In [33]:
arr.shape

(25,)

In [34]:
arr.dtype

dtype('int32')

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[0:3]

array([0, 1, 2])

In [44]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[0:5] = 100

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Numpy array indexing

In [49]:
arr = np.arange(0,11)

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[0:6] = 99

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy = arr.copy()

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_copy[:] = 100

In [64]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d

5

In [69]:
arr_2d[2][2]

45

In [70]:
arr_2d[2][1]

40

In [71]:
arr_2d[2,1]

40

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr_2d[:2,:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [75]:
arr_2d[:2,2:]

array([[15],
       [30]])

In [76]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [77]:
arr = np.arange(0,11)

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
bool_arr = arr > 5

In [81]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [82]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [84]:
arr[arr < 5]

array([0, 1, 2, 3, 4])

arr_2d = np.arange(50).reshape(5,10)

In [86]:
arr_2d 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [92]:
arr_2d[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [95]:
arr_2d[2:4][1:3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [96]:
arr_2d[2,3]

23

# Array Operations

In [97]:
arr = np.arange(0,11)

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [102]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

# universal array operattion


In [104]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [107]:
np.max(arr)

10

In [108]:
np.min(arr)

0